name: hbird
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch

dependencies:
  - python=3.11
  - pip
  - pip:
      - lightning==2.4.0
      - torchmetrics==1.7.0
      - tqdm==4.67.1
      - scipy==1.15.2
      - joblib==1.4.2
      - numpy==1.26.4
      - triton==2.2.0
      - faiss-gpu-cu12
      - scann==1.3.5
      - pyyaml>=5.0  # Required by pytorch_lightning
